markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Ubiquitous
host: frusciante.github.io
desc: 一只猿

custom:
    category:
        default: Default Category
        another: Another Category
    categories:
      - name:  default
        title: Default Category

      - name:  another
        title: Another Category

meta:
    author:
        name: Went
        email: wenweikun@gmail.com
        disqus: frusciante              # Disqus缩略标识
        gcse: 000842308497849868873:bd8abselsyu     # Google自定义搜索标识ID
        github: wenweikun@gmail.com                 # GitHub账号
        gravatar: e64fbdefc9c5622f7a991adc14c8c08b  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
